/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 public/models/MemeTruck.glb -o src/components/MemeTruck.jsx -r public 
*/

import React from 'react'
import { useGLTF } from '@react-three/drei'

export function Truck(props) {
  const { nodes, materials } = useGLTF('/models/MemeTruck.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.Object_33.geometry} material={materials['tyres.003']} />
      <mesh geometry={nodes.Object_33_1.geometry} material={materials['wheels.003']} />
      <mesh geometry={nodes.Object_34.geometry} material={materials['tyres.012']} />
      <mesh geometry={nodes.Object_34_1.geometry} material={materials['wheels.012']} />
      <mesh geometry={nodes.Object_36.geometry} material={materials['tyres.013']} />
      <mesh geometry={nodes.Object_36_1.geometry} material={materials['wheels.013']} />
      <mesh geometry={nodes.Object_38.geometry} material={materials['tyres.014']} />
      <mesh geometry={nodes.Object_38_1.geometry} material={materials['wheels.014']} />
      <mesh geometry={nodes.Object_31.geometry} material={materials['tyres.009']} />
      <mesh geometry={nodes.Object_31_1.geometry} material={materials['wheels.009']} />
      <mesh geometry={nodes.Object_28.geometry} material={materials['tyres.011']} />
      <mesh geometry={nodes.Object_28_1.geometry} material={materials['wheels.011']} />
      <mesh geometry={nodes.Object_27.geometry} material={materials['tyres.010']} />
      <mesh geometry={nodes.Object_27_1.geometry} material={materials['wheels.010']} />
      <mesh geometry={nodes.Object_25.geometry} material={materials['wheels.001']} />
      <mesh geometry={nodes.Object_25_1.geometry} material={materials['tyres.001']} />
      <mesh geometry={nodes.Object_1.geometry} material={materials.head_paint} />
      <mesh geometry={nodes.Object_1_1.geometry} material={materials.material_0} />
      <mesh geometry={nodes.Object_1_2.geometry} material={materials.full_glossy} />
      <mesh geometry={nodes.Object_1_3.geometry} material={materials.full_glass} />
      <mesh geometry={nodes.Object_1_4.geometry} material={materials.light_emit} />
      <mesh geometry={nodes.Object_1_5.geometry} material={materials.flat_black} />
      <mesh geometry={nodes.Object_1_6.geometry} material={materials.deep_black} />
      <mesh geometry={nodes.Object_1_7.geometry} material={materials.door_knob} />
      <mesh geometry={nodes.Object_1_8.geometry} material={materials.signal_light} />
      <mesh geometry={nodes.Object_1_9.geometry} material={materials.windglass} />
      <mesh geometry={nodes.Object_1_10.geometry} material={materials.gloss_black} />
      <mesh geometry={nodes.Object_1_11.geometry} material={materials['Material.003']} />
      <mesh geometry={nodes.Object_1_12.geometry} material={materials.glass} />
      <mesh geometry={nodes.Object_1_13.geometry} material={materials.diffuse_black} />
      <mesh geometry={nodes.Object_1_14.geometry} material={materials['signal_light.001']} />
      <mesh geometry={nodes.Object_1_15.geometry} material={materials.tyres} />
      <mesh geometry={nodes.Object_1_16.geometry} material={materials.wheels} />
      <mesh geometry={nodes.Object_1_17.geometry} material={materials.wheel_hub} />
      <mesh geometry={nodes.Object_13.geometry} material={materials.bodycolour} />
      <mesh geometry={nodes.Object_13_1.geometry} material={materials.UVMapped} />
    </group>
  )
}

useGLTF.preload('/models/MemeTruck.glb')
